### ISSUE TITLE
Add Russian transtation

### ISSUE THREAD

**Issue by AlexKatyukov** [Goosly/wca-certificates#10]
You can add this:
```
[
"\n\n\n",
{"text": "certificate.delegate", "bold": "true"},
" со стороны ",
{"text": "World Cube Association", "bold": "true"},
", и ",
{"text": "certificate.organizers", "bold": "true"},
", со стороны команды организаторов ",
{"text": "certificate.competitionName", "bold": "true"},
", подтверждают, что",
"\n\n\n",
{"text": "certificate.name", "fontSize": "32", "bold": "true"},
"\n\n\n",
"занял ",
{"text": "certificate.place", "bold": "true"},
" место в дисциплине ",
{"text": "certificate.event", "bold": "true"},
" с результатом ",
{"text": "certificate.result", "bold": "true"}
]
```

**Comment by Goosly** [comment]
Hey, thanks for the translations! There are added now.
I also needed a translation for first, second and third, which is inserted when the certificates are generated. I used these from google translate:
первый, второй, третий

Let me know if that needs to be changed

Here's and example:
![image](https://user-images.githubusercontent.com/12575384/67139669-06b14900-f253-11e9-9f18-03a96950b696.png)

**Comment by AlexKatyukov** [comment]
Use this to be fully correct:
первое
второе
третье

**Comment by Goosly** [comment]
Thanks, done

**Comment by Goosly** [comment]
Hey @AlexKatyukov, I've implemented a new feature and I would need the Russian translations for:
"an average"
"a mean"
"a best result"

Currently this is all translated as "результатом", which means "a result", I think?

**Comment by AlexKatyukov** [comment]
`с результатом` means `with the result`. Just `a result` should be translated as `результат`

`an average` = `среднее WCA` (we have no special word for average)
`a mean` = `среднее`
`a best result` = `лучшее`
`moves` = `ходов`

**Comment by Goosly** [comment]
Thanks! We have the same in Dutch, we only have one word for average or mean :-)

I think everything is okay now:
![image](https://user-images.githubusercontent.com/12575384/69963781-3a99b280-1511-11ea-98d4-58be91842487.png)

Could you please try with one of your competitions and check if everything is grammatically correct?

**Comment by AlexKatyukov** [comment]
Hmm. Better it will be `с лучшим результатом` for single and `со средним результатом` for mean / average.

One more problem: word `ходов` has different endings. I literally forgot about it!
1 ход
2-4 хода
5-20 ходов
21 ход
22-24 хода
25-30 ходов
31 ход
32-34 хода
35-40 ходов
41 ход
42-44 хода
45-50 ходов
51 ход
52-54 хода
55-60 ходов
61 ход
62-64 хода
65-70 ходов
71 ход
72-74 хода
75-80 ходов

And I don't know how to make it easier o_O
