### ISSUE TITLE
Non latin character issue

### ISSUE THREAD

**Issue by simonkellly** [Goosly/wca-certificates#18]
During the use of this software at a competition this weekend, I noticed that  some of the characters were not displaying properly, specifically 
![image](https://user-images.githubusercontent.com/26287997/68092889-cd4e1f80-fe87-11e9-9cc7-dc05847b884e.png)

Is there any way to avoid this?

**Comment by Goosly** [comment]
Pdfmake is used to generate the pdf's, and it seems like the font does not support this character. I'll need to investigate. Thanks for reporting!

**Comment by Goosly** [comment]
@simonkellly I won't have any time in the upcoming weeks to look into this, so as a quick workaround I've added the option to hide the local names under the "Customize text and styling" settings. Could you check if that works as expected for you?

**Comment by simonkellly** [comment]
Sorry, I never closed this, haven't had any issues since though!
