### ISSUE TITLE
"certificate.resultUnit" Not Working

### ISSUE THREAD

**Issue by sarahstrong314** [Goosly/wca-certificates#21]
This variable is an empty string.

**Comment by Goosly** [comment]
Yeah, at the moment it is only used for FMC so it would say "with a best result of 25 **moves**"

But I for other events indeed it doesn't do anything yet as I haven't really figured out what the best wording would be (e.g. for 5x5: "with an average of 55.84 seconds" and "with an average of 1:20.19 minutes"?). Then I would need to implement logic for the result being in seconds vs minutes and maybe there are other corner cases. And for multiblind there is definitely no unit to show.

**Comment by sarahstrong314** [comment]
I see. Thanks!
