### ISSUE TITLE
Old competition certificates

### ISSUE THREAD

**Issue by AlexKatyukov** [Goosly/wca-certificates#31]
Hello!

One competitor asks me to send him a participation certificate from very old (September 2019) competition. Can I do it somehow?

**Comment by Goosly** [comment]
Not yet possible. I'll think of some way to allow you to get older competitions when needed. Right now you get your own competitions of the last 4 weeks, if I remember correctly.

**Comment by AlexKatyukov** [comment]
Yes, you remember correct. Will be nice if you add this opportunity!

**Comment by Goosly** [comment]
More than 2 years later, finally done :)
