### ISSUE TITLE
Allow users to upload their own certificate design

### ISSUE THREAD

**Issue by sarahstrong314** [Goosly/wca-certificates#4]

**Comment by Goosly** [comment]
A certificate consists of 2 parts: the background and the text. The background must always be printed pre-comp (so if your printer fails at the comp, you can fall back to handwriting the text on top of the already printed background and the certificate will still look acceptable).

This tool covers generating pdf's with the text that should be printed during the competition, while logo's are part of the background, therefore not relevant here.

**Comment by sarahstrong314** [comment]
I was referring to just the background design.

**Comment by Goosly** [comment]
Yes, and what is the purpose of uploading the background that you will already have printed separately before the competition, while this tool is what you're using during the competition to print text on top of the background?

**Comment by Goosly** [comment]
Ah yeah I copied my reply from a thread on Facebook where someone was asking about logo's. Anyway, the point still stands for the background in general :-)

**Comment by sarahstrong314** [comment]
I see. I assumed the tool would be similar to cubecomps's certificate tool, which has the text on top of the background design in the file.

**Comment by sarahstrong314** [comment]
I personally think it's worth merging the text and the design onto the same file. I dislike filling in certificates by hand (it makes them look less professional), and if the text is printed onto a sheet of paper that already has the certificate design printed onto it, the ink can easily smudge and the text could get misaligned.

**Comment by AlexKatyukov** [comment]
So, for example in Russia we don't print participation certificates and just post it and everyone can print it. It's another issue about participation certificates, but possibility to print background with text can be useful.

**Comment by Goosly** [comment]
@sarahstrong314 Done with the lastest build! Can you please check it out and let me know if it works okay for you?

I recommend using a background image that has more or less the same ratio as an A4 paper, that is 297 x 210. Using something else, for example a 1920x1080 image will leave a white gap at the bottom.

**Comment by sarahstrong314** [comment]
@Goosly Thanks for taking the time to update the features! 

The background images appears to be working for me. Here's what I got when I tried it: https://github.com/Goosly/wca-certificates/files/3902816/Certificates.FMC.Americas.2019.pdf.
