### ISSUE TITLE
Allow users to modify the text and styling on the certificate 

### ISSUE THREAD

**Issue by sarahstrong314** [Goosly/wca-certificates#5]

**Comment by sarahstrong314** [comment]
Thanks for updating this @Goosly! 

Any chance the font style and size could also be customizable?

**Comment by Goosly** [comment]
I'm not sure what you want to do. You can change the size for each part separately by wrapping it in: {"text": "whatever", "fontSize": "32"}

[Pdfmake](http://pdfmake.org/#/) is used to generate the pdf. As long as the custom template you write is valid for Pdfmake, it should be good. I'd recommend you make small incremental changes until you're happy with your template and then copy and save that in a file on your computer to use for all of your future competitions.

**Comment by MissStrong** [comment]
I see. I wasn't aware of the syntax for font styles and sizes, but I'll look into it. Thanks!

**Comment by sarahstrong314** [comment]
I see. I wasn't aware of the syntax for font styles and sizes, but I'll play around with it. Thanks!
