### ISSUE TITLE
Participation certificate

### ISSUE THREAD

**Issue by AlexKatyukov** [Goosly/wca-certificates#9]
Hello!
Can you add participation certificate? It's tradition in my local community to post such certificates after competition.

**Comment by Goosly** [comment]
Could give an example (as an image or a pdf)? I assume it shows the participant's name and all of his results?

**Comment by AlexKatyukov** [comment]
[This is a PDF](https://github.com/Goosly/wca-certificates/files/3911580/YJMoscowSpecial2019_-_Participation_Certificates.pdf)

**Comment by Goosly** [comment]
Initial version done. Will probably be improved later when I get some feedback.

**Comment by AlexKatyukov** [comment]
**Thank you so much for your work!** Some kind of feedback (proposals):

1. Allow to modify certifiate text
2. Make some standart background that can be turned on with checkbox

**Comment by Goosly** [comment]
Hey @AlexKatyukov , in English the table with the obtained results looks like this:

![image](https://user-images.githubusercontent.com/12575384/75114069-3c2bd000-5653-11ea-9159-ea66a07b3391.png)

Can you let me know the Russian translations for these 3 words at the top?

**Comment by AlexKatyukov** [comment]
Sure!

`Event` = `Дисциплина`
`Result` = `Результат`
`Position` = `Место`
`has participated in (some competition), obtaining the following results:` = `принял(а) участие в [some competition], достигнув следующих результатов:`

**Comment by Goosly** [comment]
What does the a in принял(а) depend on?

**Comment by AlexKatyukov** [comment]
This word is принял for males and приняла for females. We usually use this form for gender neutral. 15:37, February 24, 2020, Manu Vereecken <notifications@github.com>:What does the a in принял(а) depend on?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by Goosly** [comment]
Okay, I see! Participation certificates in Russian is done. Can you test it to see if I made any mistakes? It's a bit hard for me to test in a language I don't know :-)

You should be able to select Izhevsk Winter Cube 2020 (the tool allows you to print up to 4 weeks after a competition)

**Comment by AlexKatyukov** [comment]
Nice!

You forgot about comma `,` after competition name. Another part is good.

Thank you for your work.

**Comment by Goosly** [comment]
Comma added :-)
